name: Playwright Tests
on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'halcyon_land_dev'
          mysql root password: 'Pass'

      - name: Install dependencies
        run: npm install && sudo apt update && sudo apt install mysql-server

      - name: Set root password
        run: sudo mysql -h 127.0.0.1 -u root -pPass -e "ALTER USER 'root'@'%' IDENTIFIED BY ''"

      - name: Run migrations
        run: sudo mysql -h 127.0.0.1 -u root halcyon_land_dev < ./db/schema.sql

      - name: Install Playwright browsers
        run: npx playwright install msedge && npx playwright install chromium && npx playwright install firefox

      - name: Install Playwright system dependencies
        run: npx playwright install-deps

      - name: Run Playwright tests
        run: bin/test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
