name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'misc_3_dev'
          mysql root password: 'Pass'

      - name: logs
        run: sudo apt-get install mysql-server

      - name: Start MySql socket
        run: sudo systemctl start mysql

      - name: Install dependencies
        run: npm i -g pnpm && pnpm install && sudo apt update && sudo apt install mysql-server

      - name: Create database
        run: sudo mysql -u root -pPass -e "ALTER USER 'root'@'localhost' IDENTIFIED BY ''"

      - name: Run migrations
        run: mysql -u root misc_3_dev < schema.sql

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
